spring:
  application:
    name: accounts
    version: v1_0_0
    base-path: "/microservice/accounts/"
  config:
    activate:
      on-profile: "prod"
custom:
  config:
    application:
      info:
        owner: Dhamu
        contact: "62302742"
        company: UST
        env: Prodbus
        contacts:
          - 245432
          - 455432
